import json
import tempfile
import unittest
from pathlib import Path

from ga_release import ReleaseError, build_notes, complete_release, ensure_not_published


VERSION = "0.10.92"
REPO = "wey-gu/mem-releases"
ASSETS = [
    f"Nowledge.Mem_{VERSION}_aarch64.dmg",
    f"Nowledge.Mem_{VERSION}_x64.dmg",
    f"Nowledge.Mem_{VERSION}_x64-setup.exe",
    f"Nowledge.Mem_{VERSION}_amd64.deb",
    f"Nowledge.Mem_{VERSION}_amd64.AppImage",
]


class GaReleaseTest(unittest.TestCase):
    def test_notes_require_the_exact_deployed_changelog_version(self):
        payload = {
            "version": VERSION,
            "found": True,
            "title": "A safer release",
            "release_notes": "- Reliable updates\n- Clearer recovery",
        }
        self.assertIn("Reliable updates", build_notes(payload, VERSION))
        self.assertIn(f"https://mem.nowledge.co/changelog#{VERSION}", build_notes(payload, VERSION))
        with self.assertRaises(ReleaseError):
            build_notes({**payload, "version": "0.10.91"}, VERSION)
        with self.assertRaises(ReleaseError):
            build_notes({**payload, "release_notes": ""}, VERSION)

    def test_publishes_a_complete_draft_and_verifies_latest(self):
        calls = []
        release = {
            "id": 42,
            "tag_name": f"v{VERSION}",
            "draft": True,
            "prerelease": False,
            "body": "Promoted from v0.10.92-rc1. Generated by promote-rc-to-ga.",
            "assets": [{"name": name} for name in ASSETS],
        }

        def gh(args):
            calls.append(args)
            if any("releases?per_page=100" in arg for arg in args):
                return json.dumps([release])
            if args[-1] == "repos/wey-gu/mem-releases/releases/latest":
                return json.dumps({"tag_name": f"v{VERSION}"})
            if "-F" in args and "draft=false" in args:
                release["draft"] = False
                release["published_at"] = "2026-09-30T02:00:00Z"
            return json.dumps(release)

        with tempfile.TemporaryDirectory() as directory:
            notes = Path(directory) / "notes.md"
            notes.write_text("# A safer release\n", encoding="utf-8")
            complete_release(VERSION, REPO, notes, latest=True, gh=gh)
            published_notes = notes.read_text(encoding="utf-8")

        self.assertTrue(any("draft=false" in call for call in calls))
        self.assertTrue(any("make_latest=true" in call for call in calls))
        self.assertTrue(any("--notes-file" in call for call in calls))
        self.assertIn("Promoted from v0.10.92-rc1", published_notes)
        self.assertIn("RPM availability is pending", published_notes)

    def test_does_not_publish_a_missing_asset_or_an_existing_public_release(self):
        calls = []
        release = {
            "id": 42,
            "tag_name": f"v{VERSION}",
            "draft": True,
            "prerelease": False,
            "body": "Reviewed release notes",
            "assets": [{"name": name} for name in ASSETS[:-1]],
        }

        def gh(args):
            calls.append(args)
            return json.dumps([release])

        with tempfile.TemporaryDirectory() as directory:
            notes = Path(directory) / "notes.md"
            notes.write_text("# A safer release\n", encoding="utf-8")
            with self.assertRaises(ReleaseError):
                complete_release(VERSION, REPO, notes, latest=True, gh=gh)
        self.assertFalse(any("draft=false" in call for call in calls))

        release["draft"] = False
        with self.assertRaises(ReleaseError):
            ensure_not_published(VERSION, REPO, gh=gh)

    def test_out_of_band_release_preserves_reviewed_notes_and_latest(self):
        calls = []
        release = {
            "id": 42,
            "tag_name": f"v{VERSION}",
            "draft": True,
            "prerelease": False,
            "body": "Reviewed release notes",
            "assets": [{"name": name} for name in ASSETS],
        }

        def gh(args):
            calls.append(args)
            if any("releases?per_page=100" in arg for arg in args):
                return json.dumps([release])
            if args[-1] == "repos/wey-gu/mem-releases/releases/latest":
                return json.dumps({"tag_name": "v0.10.91"})
            if "-F" in args and "draft=false" in args:
                release["draft"] = False
                release["published_at"] = "2026-09-30T02:00:00Z"
            return json.dumps(release)

        with tempfile.TemporaryDirectory() as directory:
            notes = Path(directory) / "notes.md"
            notes.write_text("# Generated notes\n", encoding="utf-8")
            complete_release(VERSION, REPO, notes, latest=False, gh=gh)

        self.assertFalse(any("--notes-file" in call for call in calls))
        self.assertTrue(any("make_latest=false" in call for call in calls))


if __name__ == "__main__":
    unittest.main()
